apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tomcat-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: tomcat
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /usr/local/tomcat/conf
          name: tomcat-config
        envFrom:
        - configMapRef:
            name: tomcat-configmap
        - secretRef:
            name: tomcat-secret
      volumes:
      - name: tomcat-config
        persistentVolumeClaim:
          claimName: tomcat-pvc