global:
  imageRegistry: "docker.io"

fullnameOverride: kafka
clusterDomain: "cluster.local"

image:
  repository: bitnami/kafka
  tag: 3.6.1-debian-12-r11
  pullPolicy: IfNotPresent
  debug: false

listeners:
  client:
    protocol: "PLAINTEXT"
  controller:
    protocol: "PLAINTEXT"

controller:
  replicaCount: 5
  podManagementPolicy: Parallel

metrics:
  kafka:
    enabled: true
    image:
      repository: bitnami/kafka-exporter
      tag: 1.7.0-debian-12-r18
      pullPolicy: IfNotPresent

  jmx:
    enabled: true
    image:
      repository: bitnami/jmx-exporter
      tag: 0.20.0-debian-12-r11

topics:
  - name: primer-topic
    partitions: 10
    replicationFactor: 5
    config:
      max.message.bytes: 32000