replicaCount: 2

image:
  repository: fernandogg99/http-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: http-app.local
      paths:
        - /
  tls: []

ingressController:
  enabled: false
  extraArgs:
    publish-status-address: localhost
  hostPort:
    enabled: true
  publishService:
    enabled: false
  service:
    type: NodePort
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
      operator: Equal
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
      operator: Equal
  watchIngressWithoutClass: true
  nodeSelector:
    ingress-ready: "true"
    kubernetes.io/os: linux
