version: '3.8'

services:
  payload:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./payload.json:/app/payload.json
      - ./payload.py:/app/payload.py
    command: python payload.py