apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
      annotations: {{ .Values.podAnnotations | toYaml | nindent 8 }}
    spec:
      securityContext: {{ .Values.podSecurityContext | toYaml | nindent 6 }}
      nodeSelector: {{ .Values.nodeSelector | toYaml | nindent 6 }}
      tolerations: {{ .Values.tolerations | toYaml | nindent 6 }}
      affinity: {{ .Values.affinity | toYaml | nindent 6 }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        resources: {{ .Values.resources | toYaml | nindent 10 }}
        securityContext: {{ .Values.securityContext | toYaml | nindent 10 }}
