{{- if .Values.ingressController.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ingress-nginx
  namespace: ingress-nginx
  labels:
    app: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-nginx
  template:
    metadata:
      labels:
        app: ingress-nginx
    spec:
      containers:
      - name: ingress-nginx
        image: k8s.gcr.io/ingress-nginx/controller:v1.7.0
        args:
          {{- range $key, $value := .Values.ingressController.extraArgs }}
          - --{{ $key }}={{ $value }}
          {{- end }}
        ports:
          - name: http
            containerPort: 80
          - name: https
            containerPort: 443
        {{- if .Values.ingressController.hostPort.enabled }}
        hostNetwork: true
        {{- end }}
        tolerations:
          {{- range .Values.ingressController.tolerations }}
          - key: {{ .key }}
            operator: {{ .operator }}
            effect: {{ .effect }}
          {{- end }}
        nodeSelector:
          {{- range $key, $value := .Values.ingressController.nodeSelector }}
          {{ $key }}: {{ $value }}
          {{- end }}
      serviceAccountName: ingress-nginx

apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  type: {{ .Values.ingressController.service.type }}
  ports:
    - port: 80
      targetPort: http
    - port: 443
      targetPort: https
  selector:
    app: ingress-nginx
{{- end }}